version: '3.8'

services:
  site:
    image: nginx:alpine
    ports:
      - "5500:80"
    volumes:
      - ./site:/usr/share/nginx/html:ro
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "3002:3002"
    volumes:
      - ./api/invoices:/app/invoices
      - ./api/banksim:/app/banksim
      - ./api/data:/app/data
    env_file:
      - ./api/.env
    environment:
      - NODE_ENV=development